show databases;
use customer_behaviour;
show tables;
select * from customer limit 20;

#What is the total revenue generated by male and female  customer?
select gender,sum(purchase_amount) as total_amount from customer group by gender;
select * from customer;

#which customers used discount but still spended more than average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied='yes' and purchase_amount >= (select avg(purchase_amount) from customer);

#which are the top 5 products with the highest average rating?
select item_purchased,round(avg(cast(review_rating as decimal(10,2))),2) as review_avg
from customer 
group by item_purchased
order by review_avg desc
limit 5;

#Lowest
select item_purchased,round(avg(cast(review_rating as decimal(10,2))),2) as review_low
from customer
group by item_purchased
order by review_low asc
limit 5;

#Compare the average purchase amount between standaed and express delivery?
select shipping_type,round(avg(purchase_amount),2)
from customer
where shipping_type in('Standard','Express')
group by shipping_type;

select * from customer;

# do Subscribed  customers spend more? compare average spend and total revenue between subscribers and non-subscribers?
select subscription_status,count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spended,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue desc,avg_spended desc;


#which 5 products have the highest percentage of purchase with discount applied?
select item_purchased,
round(100*sum(case when discount_applied='yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

#Customer churning to see who are loyal,new and return?
with customer_type as(
select customer_id,previous_purchases,
case 
when previous_purchases =1 then'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment
from customer
)
select customer_segment,count(*) as 'number of customers'
from customer_type
group by customer_segment;

select * from customer;
select distinct category from customer;

#What are the top 3 most purchased products withi each category?
with items_count as(
select category,item_purchased, count(customer_id) as total_orders,
row_number()over(partition by category order by count(customer_id)desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from items_count
where item_rank <=3;

#are the customers who are repeated buyers(more than 5 previous purchase) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyer
from customer
where previous_purchases > 5
group by subscription_status;


#what are the revenue from each group?
select age_group,sum(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;